language: node_js
node_js:
  - stable
  - '10'
  - '8'

install:
  - yarn install

script:
  - yarn run lint

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  on:
    tags: true
    repo: briansokol/eslint-config
    branch: master
  tag: next
