language: node_js
node_js:
  - 17

before_install:
  - npm install -g npm@8

install:
  - npm ci

script:
  - npm run build-ts
  - npm run lint:react
  - npm run lint:node
  - npm run lint:react-native
  - npm run lint:jest

deploy:
  skip_cleanup: true
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  on:
    tags: true
    repo: briansokol/eslint-config
    branch: master
